export const nodeDataArray = [
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/c/c7/Kinggeorgev1928.jpg",
    key: 0,
    firstName: "George V",
    lastName: "",
    reign: "1910-1936",
    birthDate: "01/01/1865",
    deathDate: "01/01/1936",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/5/51/Prince-Edward-Duke-of-Windsor-King-Edward-VIII.jpg",
    key: 1,
    parent: 0,
    firstName: "Edward VIII",
    lastName: "",
    reign: "1936",
    birthDate: "01/01/1894",
    deathDate: "01/01/1972",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/7/73/Georg_VI_England.jpg",
    key: 2,
    parent: 0,
    firstName: "George VI",
    lastName: "",
    reign: "1936-1952",
    birthDate: "01/01/1895",
    deathDate: "01/01/1952",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/5/50/Queen_Elizabeth_II_March_2015.jpg",
    key: 7,
    parent: 2,
    firstName: "Elizabeth II",
    lastName: "",
    reign: "1952-",
    birthDate: "01/01/1926",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/e/e2/2019_Reuni%C3%A3o_Bilateral_com_o_Pr%C3%ADncipe_Charles_-_48948389972_%28cropped%29.jpg",
    key: 16,
    parent: 7,
    firstName: "Charles, Prince of Wales",
    lastName: "",
    reign: "",
    birthDate: "01/01/1948",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Prince_William%2C_Duke_of_Cambridge.jpg",
    key: 38,
    parent: 16,
    firstName: "Prince William",
    lastName: "",
    reign: "",
    birthDate: "01/01/1982",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/3/32/Lancering_Invictus_Games_2020-7_%28cropped%29.jpg",
    key: 39,
    parent: 16,
    firstName: "Prince Harry of Wales",
    lastName: "",
    reign: "",
    birthDate: "01/01/1984",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/7/76/Princess_Anne_October_2015.jpg",
    key: 17,
    parent: 7,
    firstName: "Anne, Princess Royal",
    lastName: "",
    reign: "",
    birthDate: "01/01/1950",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 40,
    parent: 17,
    firstName: "Peter Phillips",
    lastName: "",
    reign: "",
    birthDate: "01/01/1977",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 82,
    parent: 40,
    firstName: "Savannah Phillips",
    lastName: "",
    reign: "",
    birthDate: "01/01/2010",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo:
      "https://upload.wikimedia.org/wikipedia/commons/b/bf/Zara_Phillips_%282012%29.jpg",
    key: 41,
    parent: 17,
    firstName: "Zara Phillips",
    lastName: "",
    reign: "",
    birthDate: "01/01/1981",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 18,
    parent: 7,
    firstName: "Prince Andrew",
    lastName: "",
    reign: "",
    birthDate: "01/01/1960",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 42,
    parent: 18,
    firstName: "Princess Beatrice of York",
    lastName: "",
    reign: "",
    birthDate: "01/01/1988",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 43,
    parent: 18,
    firstName: "Princess Eugenie of York",
    lastName: "",
    reign: "",
    birthDate: "01/01/1990",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 19,
    parent: 7,
    firstName: "Prince Edward",
    lastName: "",
    reign: "",
    birthDate: "01/01/1964",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 44,
    parent: 19,
    firstName: "Lady Louise Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2003",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 45,
    parent: 19,
    firstName: "James, Viscount Severn",
    lastName: "",
    reign: "",
    birthDate: "01/01/2007",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 8,
    parent: 2,
    firstName: "Princess Margaret",
    lastName: "",
    reign: "",
    birthDate: "01/01/1930",
    deathDate: "01/01/2002",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 20,
    parent: 8,
    firstName: "David Armstrong-Jones",
    lastName: "",
    reign: "",
    birthDate: "01/01/1961",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 21,
    parent: 8,
    firstName: "Lady Sarah Chatto",
    lastName: "",
    reign: "",
    birthDate: "01/01/1964",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 46,
    parent: 21,
    firstName: "Samuel Chatto",
    lastName: "",
    reign: "",
    birthDate: "01/01/1996",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 47,
    parent: 21,
    firstName: "Arthur Chatto",
    lastName: "",
    reign: "",
    birthDate: "01/01/1999",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 3,
    parent: 0,
    firstName: "Mary, Princess Royal",
    lastName: "",
    reign: "",
    birthDate: "01/01/1897",
    deathDate: "01/01/1965",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 9,
    parent: 3,
    firstName: "George Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1923",
    deathDate: "01/01/2011",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 22,
    parent: 9,
    firstName: "David Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1950",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 48,
    parent: 22,
    firstName: "Emily Shard",
    lastName: "",
    reign: "",
    birthDate: "01/01/1975",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 49,
    parent: 22,
    firstName: "Benjamin Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1978",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 50,
    parent: 22,
    firstName: "Alexander Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1980",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 51,
    parent: 22,
    firstName: "Edward Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1982",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 23,
    parent: 9,
    firstName: "James Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1953",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 52,
    parent: 23,
    firstName: "Sophie Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1973",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 53,
    parent: 23,
    firstName: "Rowan Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1977",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 54,
    parent: 23,
    firstName: "Tanit Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1981",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 55,
    parent: 23,
    firstName: "Tewa Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1985",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 24,
    parent: 9,
    firstName: "Jeremy Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1955",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 56,
    parent: 24,
    firstName: "Thomas Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1982",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 57,
    parent: 24,
    firstName: "Ellen Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1984",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 58,
    parent: 24,
    firstName: "Amy Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1986",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 59,
    parent: 24,
    firstName: "Tallulah Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/2005",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 25,
    parent: 9,
    firstName: "Mark Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1964",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 60,
    parent: 25,
    firstName: "Charlotte Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1996",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 61,
    parent: 25,
    firstName: "Imogen Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1998",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 62,
    parent: 25,
    firstName: "Miranda Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/2000",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 10,
    parent: 3,
    firstName: "Gerald Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1924",
    deathDate: "01/01/1998",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 26,
    parent: 10,
    firstName: "Henry Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1953",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 63,
    parent: 26,
    firstName: "Maximilian Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1991",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 27,
    parent: 10,
    firstName: "Martin David Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/1962",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 64,
    parent: 27,
    firstName: "Alexander Lascelles",
    lastName: "",
    reign: "",
    birthDate: "01/01/2002",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 4,
    parent: 0,
    firstName: "Prince Henry",
    lastName: "",
    reign: "",
    birthDate: "01/01/1900",
    deathDate: "01/01/1974",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 11,
    parent: 4,
    firstName: "Prince William of Gloucester",
    lastName: "",
    reign: "",
    birthDate: "01/01/1941",
    deathDate: "01/01/1972",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 12,
    parent: 4,
    firstName: "Prince Richard",
    lastName: "",
    reign: "",
    birthDate: "01/01/1944",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 28,
    parent: 12,
    firstName: "Alexander Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1974",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 65,
    parent: 28,
    firstName: "Xan Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2007",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 66,
    parent: 28,
    firstName: "Lady Cosima Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2010",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 29,
    parent: 12,
    firstName: "Lady Davina Lewis",
    lastName: "",
    reign: "",
    birthDate: "01/01/1977",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 67,
    parent: 29,
    firstName: "Senna Lewis",
    lastName: "",
    reign: "",
    birthDate: "01/01/2010",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 30,
    parent: 12,
    firstName: "Lady Rose Gilman",
    lastName: "",
    reign: "",
    birthDate: "01/01/1980",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 68,
    parent: 30,
    firstName: "Lyla Gilman",
    lastName: "",
    reign: "",
    birthDate: "01/01/2010",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 5,
    parent: 0,
    firstName: "Prince George",
    lastName: "",
    reign: "",
    birthDate: "01/01/1902",
    deathDate: "01/01/1942",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 13,
    parent: 5,
    firstName: "Prince Edward",
    lastName: "",
    reign: "",
    birthDate: "01/01/1935",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 31,
    parent: 13,
    firstName: "George Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1962",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 69,
    parent: 31,
    firstName: "Edward Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1988",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 70,
    parent: 31,
    firstName: "Lady Marina-Charlotte Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1992",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 71,
    parent: 31,
    firstName: "Lady Amelia Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1995",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 32,
    parent: 13,
    firstName: "Lady Helen Taylor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1964",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 72,
    parent: 32,
    firstName: "Columbus Taylor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1994",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 73,
    parent: 32,
    firstName: "Cassius Taylor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1996",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 74,
    parent: 32,
    firstName: "Eloise Taylor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2003",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 75,
    parent: 32,
    firstName: "Estella Taylor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2004",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 33,
    parent: 13,
    firstName: "Lord Nicholas Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1970",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 76,
    parent: 33,
    firstName: "Albert Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2007",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 77,
    parent: 33,
    firstName: "Leopold Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/2009",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 14,
    parent: 5,
    firstName: "Princess Alexandra",
    lastName: "",
    reign: "",
    birthDate: "01/01/1936",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 34,
    parent: 14,
    firstName: "James Ogilvy",
    lastName: "",
    reign: "",
    birthDate: "01/01/1964",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 78,
    parent: 34,
    firstName: "Flora Ogilvy",
    lastName: "",
    reign: "",
    birthDate: "01/01/1994",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 79,
    parent: 34,
    firstName: "Alexander Ogilvy",
    lastName: "",
    reign: "",
    birthDate: "01/01/1996",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 35,
    parent: 14,
    firstName: "Marina Ogilvy",
    lastName: "",
    reign: "",
    birthDate: "01/01/1966",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 80,
    parent: 35,
    firstName: "Zenouska Mowatt",
    lastName: "",
    reign: "",
    birthDate: "01/01/1990",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 81,
    parent: 35,
    firstName: "Christian Mowatt",
    lastName: "",
    reign: "",
    birthDate: "01/01/1993",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 15,
    parent: 5,
    firstName: "Prince Michael of Kent",
    lastName: "",
    reign: "",
    birthDate: "01/01/1942",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 36,
    parent: 15,
    firstName: "Lord Frederick Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1979",
    deathDate: "",
    gender: "male",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 37,
    parent: 15,
    firstName: "Lady Gabriella Windsor",
    lastName: "",
    reign: "",
    birthDate: "01/01/1981",
    deathDate: "",
    gender: "female",
    w: 250,
    h: 60,
  },
  {
    photo: "",
    key: 6,
    parent: 0,
    firstName: "Prince John",
    lastName: "",
    reign: "",
    birthDate: "01/01/1905",
    deathDate: "01/01/1919",
    gender: "male",
    w: 250,
    h: 60,
  },
];
export const linkDataArray = nodeDataArray
  .filter((member) => member.parent !== undefined)
  .map(({ key, parent }) => ({
    from: parent,
    to: key,
    parent: "parent",
    child: "child",
  }));
